dist: xenial
language: node_js
cache: npm
os:
- linux
env:
  global:
  - secure: FMoZAxhX7crjYaQdekyb3NOIVySMApq8eotFJnq96IwVEY0HMQ6iy4C/m/wUimdNcrYJSZZycy3fTXD3MX+3gMn6rQ0ftrRP2+F12jzaOjur/eaq/yDLmQ6u9WrXV45bgxhlDBndOOPs3Xn7qbv7jwb/iedQO9jUY8/w1rsxCsGAvf3LhF94dhunKEgfmJGp9nWt9yUaRt/i2hKBOW8hXcRBzM4j+aXRUUIgRouavWElw463YZ3OtA9leGEldnULEXZPuJSAhR5AKXgS7d9F7lLCByUDX7JnRfxHHAcxyO1GCdx40nmhjbmD/LXht7ZJaTyAHYF+2MXi4bxuPF433RpxLSe+zxnT3VxZp/nJmpwqG+lW3okOIzJ49O+zT731X1gd3sxazzYrY9bAyg3shLtt1dlL6XGwwYVpDTbrEEsdP1mVAceoQkt+pcM564XDniPFKIOFIk3Up1aZCupYgS/LGqYd2sUyWy/OgCfPTDy1A5bTbZlpZjU1kKZ4rvyp1Duq2/rjKgkdzT6YXLUdjKvkygLBALs2ZeCirfTa2M66yGvX7c3IlU6NSRBVYQMsZ98F+l4mcIRmsBfkbHKi4xKqbj6arMY7D/lKMHY+6IbrfiFkYa1znDoMkQZEtdYpx2OWiq2m8mIx/GT/Ik0Mrq7O0DDUh9PzMwqEMk3uUao=
node_js:
- '10'
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
script:
- npm test
- npm run coverage
after_success:
- ./cc-test-reporter after-build -t lcov
