#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

get_npm_module_tarball() {
    npm view $1 dist.tarball | tail -n1 | sed -e "s/.*'\(.*\)\'/\1/"
}

wget_unpack() {
    local dest=$([ -z "$2" ] && echo "tmp" || echo "$2")
    mkdir -p "$dest" && wget -qO- $1 | tar xz - -C "$dest" --strip-components 1;
    echo "$dest"
}

install_webpack_temp() {
  npm i -C $(wget_unpack $(get_npm_module_tarball webpack@$1) tmp/webpack@$1) --production --ignore-scripts > /dev/null
}
# collects webpack plugin list with the following format
# {pluginJPath} {pluginFilename}
# .....
# if {pluginFilename} is empty , the plugin is considered deprecated
collects_webpack_plugins() {
    $SCRIPT_DIR/collects-plugin-list ./tmp/webpack@$1 \
    | xargs -L 1 -I {} \
        bash -c 'echo $2 $(find "tmp/webpack@$1" -type f -name "${2##*.}.js"|sed -e "s/^tmp\/webpack@$1\///")' -a $1 {}
}

collects_webpack_plugins_from_dir() {
  find "tmp/webpack@$1/lib" -name '*Plugin.js' \
    | sed -e "s/^tmp\/webpack@$1\///" \
    | xargs -L 1 -I {} \
      bash -c 'printf "%s %s\n" $(sed -e "s/^lib\/\(.*\)\.js/\1/" <<<"{}" |tr "/" ".") "{}"'; 
}
format_plugin_json() { 
  jq --slurp --raw-input 'split("\n")[:-1]|map({name: split(" ")[0], filename: split(" ")[1]})'
}
format_plugin_js() {
  $SCRIPT_DIR/format-plugin-source $@
}

echo >&2 "Generating webpack@4 plugins list"
install_webpack_temp 4
# Auto insertion for unreferenced plugins in webpack 4 using file matching
cat \
  <(collects_webpack_plugins 4) \
  <(collects_webpack_plugins_from_dir 4) \
  | sort -u -k1 | tee >(format_plugin_js 4 > wp-plugins-v4.js) >(format_plugin_json > wp-plugins-v4.json)
echo >&2 "Generating webpack@5 plugins list"
install_webpack_temp 5
collects_webpack_plugins 5 \
  | sort -u -k1 | tee >(format_plugin_js 5 > wp-plugins-v5.js) >(format_plugin_json > wp-plugins-v5.json)
rm -rf tmp


# collects_webpack_plugins 5 | sort -u -k1 | format_plugin_js 5 > 
